#ifndef HILBERT_CURVE_GENERATOR_GLFW_HPP
#define HILBERT_CURVE_GENERATOR_GLFW_HPP

#define GLFW_INCLUDE_GLCOREARB
#define GL_GLEXT_PROTOTYPES

#include <GLFW/glfw3.h>

#endif //HILBERT_CURVE_GENERATOR__GLFW_HPP
