//
// Created by rowan on 05/10/17.
//

#ifndef CPSC_453_ASSIGNMENT_1_SHADERPROGRAM_HPP
#define CPSC_453_ASSIGNMENT_1_SHADERPROGRAM_HPP


class ShaderProgram {

};


#endif //CPSC_453_ASSIGNMENT_1_SHADERPROGRAM_HPP
