//
// Created by rowan on 05/10/17.
//

#ifndef CPSC_453_ASSIGNMENT_1_VERTEXBUFFER_HPP
#define CPSC_453_ASSIGNMENT_1_VERTEXBUFFER_HPP


class VertexBuffer {

};


#endif //CPSC_453_ASSIGNMENT_1_VERTEXBUFFER_HPP
